//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenBay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuyenBay()
        {
            this.PhieuDatVes = new HashSet<PhieuDatVe>();
        }
    
        public int MaChuyenBay { get; set; }
        public Nullable<System.DateTime> NgayCatCanh { get; set; }
        public Nullable<System.TimeSpan> GioCatCanh { get; set; }
        public Nullable<System.TimeSpan> ThoiGianBay { get; set; }
        public string LoaiMayBay { get; set; }
        public int MaChangBay { get; set; }
        public Nullable<decimal> GiaNguoiLon { get; set; }
        public Nullable<decimal> GiaTreEm { get; set; }
    
        public virtual ChangBay ChangBay { get; set; }
        public virtual MayBay MayBay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDatVe> PhieuDatVes { get; set; }
    }
}
