//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHoaDon { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<int> MaVe { get; set; }
        public string MaHinhThucTT { get; set; }
        public Nullable<int> MaTTXuat { get; set; }
        public Nullable<int> MaKhuyenMai { get; set; }
    
        public virtual HinhThucThanhToan HinhThucThanhToan { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual ThongTinXuatHoaDon ThongTinXuatHoaDon { get; set; }
        public virtual Ve Ve { get; set; }
    }
}
