//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang_DatVe
    {
        public int MaPhieuDatVe { get; set; }
        public int MaKH { get; set; }
        public int NguoiDat { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual PhieuDatVe PhieuDatVe { get; set; }
    }
}
