//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatVeMayBayEntities : DbContext
    {
        public DatVeMayBayEntities()
            : base("name=DatVeMayBayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<ChangBay> ChangBays { get; set; }
        public virtual DbSet<ChuyenBay> ChuyenBays { get; set; }
        public virtual DbSet<HanhLy> HanhLies { get; set; }
        public virtual DbSet<HinhThucThanhToan> HinhThucThanhToans { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<KhuyenMai> KhuyenMais { get; set; }
        public virtual DbSet<LoaiVe> LoaiVes { get; set; }
        public virtual DbSet<MayBay> MayBays { get; set; }
        public virtual DbSet<NganHang> NganHangs { get; set; }
        public virtual DbSet<PhieuDatVe> PhieuDatVes { get; set; }
        public virtual DbSet<SanBay> SanBays { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThongTinXuatHoaDon> ThongTinXuatHoaDons { get; set; }
        public virtual DbSet<Ve> Ves { get; set; }
        public virtual DbSet<KhachHang_DatVe> KhachHang_DatVe { get; set; }
        public virtual DbSet<PhieuDatVe_HanhLy> PhieuDatVe_HanhLy { get; set; }
    }
}
