//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDatVe_HanhLy
    {
        public int MaPhieuDatVe { get; set; }
        public string MaHanhLy { get; set; }
        public int SoLuong { get; set; }
    
        public virtual HanhLy HanhLy { get; set; }
        public virtual PhieuDatVe PhieuDatVe { get; set; }
    }
}
